services:
  web:
    image: maxpolak04/taskmanager-app:v1.0
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - flasknet

  db:
    image: mysql:8.3
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: taskmanager
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - flasknet

  nginx:
    image: maxpolak04/flaskgate:v1.0
    container_name: flask_nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - flasknet

  redis:
    image: redis:7-alpine
    container_name: flask_redis
    ports:
      - "6379:6379"
    networks:
      - flasknet


volumes:
  db_data:

networks:
  flasknet:
