services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    # volumes:
    #   - ./app:/app
    networks:
      - flasknet

  db:
    image: mysql:8.3
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: taskmanager
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - flasknet

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    depends_on:
      - web
    networks:
      - flasknet

volumes:
  db_data:

networks:
  flasknet:
